mainブランチのアップデート
haw/workshop pull request #6
Opened 2024-05-21 00:27 UTC by tsuruoka91

- バージョンアップ
- READMEの分割、内容の更新

2024-05-21 07:39 UTC, yamauchi-haw requested changes
私が勘違いしているところがありましたら申し訳ないのですが、通しで確認しようとしたら詰まってしまったので、確認したところまでで一旦お戻しします。

2024-05-21 07:39 UTC, yamauchi-haw commented on README.md
> +git checkout -b cli origin/workshop20xx (※20xxの部分は年度毎に変更)
`git branch -r`をしても、 `origin/workshop2024`がありませんでした。
とりあえずブランチの切り替えは気にせず続行します。

2024-05-21 07:39 UTC, yamauchi-haw commented on README.md
> +git status でブランチがworkshop20xx であることを確認
```suggestion
git status でブランチがorigin/workshop20xx であることを確認
```

のほうが丁寧だと思います。

2024-05-21 07:39 UTC, yamauchi-haw commented on README.md
>  docker compose run --rm web bin/rails db:create
Imageがなければ作るということでしょうし、前からなかったのだとおもいますが、基本に忠実に、
`docker compose build`
のステップをいれることにしておきましょう。

2024-05-21 07:39 UTC, yamauchi-haw commented on doc/work1.md
> +docker compose exec web bin/rails api:get_addresses
```
rails aborted!
Don't know how to build task 'api:get_addresses' (See the list of available tasks with `rails --tasks`)

(See full trace by running task with --trace)
```

でした。
lib/tasks にファイルがありませんでした。

origin/workshop2024からチェックアウトしていないせいかもしれません。

2024-05-22 02:12 UTC, tsuruoka91 commented on README.md
> +git checkout -b cli origin/workshop20xx (※20xxの部分は年度毎に変更)
workshop2024を追加しました。

2024-05-22 07:13 UTC, yamauchi-haw requested changes
work1.mdまで確認しました。一旦ここまでで結果を戻します。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +{:count=>0, :addresses=>[]}
`nil`が返ります。
以下のいずれかを対応してください。

- `origin/workshop2024`ブランチであらかじめ、TapyrusApi::get_addresses を実装しておく
- TapyrusApi::get_addressesの実装もワークでさせるのなら、その進行にあうようにREADMEを更新する

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +https://doc.api.tapyrus.chaintope.com/#tag/address/operation/createAddress
```suggestion
https://doc.api.tapyrus.chaintope.com/#operation/createAddress
```

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +実行結果として以下のように、新規発行されたアドレスが表示されれば正しく実装されています。
```suggestion
実行結果として以下のように、新規発行されたアドレスが表示されれば正しく実装されています。
以下はあくまでも例ですので、実行の都度異なるアドレスが発行されます。
```

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +https://doc.api.tapyrus.chaintope.com/#tag/token/operation/issueToken
```suggestion
https://doc.api.tapyrus.chaintope.com/#operation/issueTokenV2
```

先行してv2のリンクにしておきました。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +実行結果として以下のように、新規発行されたトークンの ID とトークン新規発行のために発行された transaction の id が表示されれば、正しく実装できています。
```suggestion
実行結果として以下のように、新規発行されたトークンの ID とトークン新規発行のために発行された transaction の id が表示されれば、正しく実装できています。
以下はあくまでも例ですので、`token_id`と`txid`は実行の都度変わります。
```

例だということを強調しておいてもらえるとよいと思いました。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +https://doc.api.tapyrus.chaintope.com/#tag/token/operation/reissueToken
```suggestion
https://doc.api.tapyrus.chaintope.com/#operation/issueTokenV2
```

先行してv2のリンクにしておきました。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +https://doc.api.tapyrus.chaintope.com/#tag/token/operation/getTokens
```suggestion
https://doc.api.tapyrus.chaintope.com/#operation/getTokensV2
```
先行してv2のリンクにしておきました。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +以下のように、所持しているトークンの ID と総量が表示されれば、正しく実装できています。
あくまでも例であることを一文足しておいてください。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +自分のアドレスに送付した人は、発行時と変わらないと思いますが、他人のアドレスに送付した人は自分が発行したトークンが減少しています。
ここまでのworkで自分のアドレス宛に送付という操作はでてこないので、消すか、そのワークを間にいれてください。

2024-05-22 07:13 UTC, yamauchi-haw commented on doc/work1.md
> +これでコマンドが実行できるようになりました。以下のコマンドを実行してトークンを確認しましょう。
単なるコメントです。本番用のTapyrus APIを使うと10分程度待たないと発行されないと思います。

2024-05-22 07:13 UTC, yamauchi-haw commented on lib/utils/tapyrus_api.rb
> -
lib/utils/tapyrus_api.rb
のクラスメソッドはワークで触る順に並べ替えておくとよいとおもいます。


feature/main-update
workshop2024

ともに順番をあわせておいてください。

2024-05-22 07:59 UTC, yamauchi-haw commented on config/database.yml
> +  database: workshop_development
35行目のコメントの `202207` もとっておきましょうか。

2024-05-22 09:11 UTC, tsuruoka91 commented on lib/utils/tapyrus_api.rb
> -
work1とwork2でこの実装の順番が異なっていたので、検討しています。

2024-05-24 02:39 UTC, yamauchi-haw requested changes
doc/work2.mdに10件コメントしました。
+ あわせて以下のコメントにご対応ください。

https://github.com/haw/workshop/pull/6/files#r1607795091

https://github.com/haw/workshop/pull/6/files#r1609403443

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +  res.body
```suggestion
  res.body[:tokens]
```

v2に変えたあと動作を確認されていますか……？

origin/feature/main-updateのapp/controllers/tokens_controller.rb側で対処しているわけでもなさそうなので、v2に変えたあとの動作確認をしていないのではないかと疑ってしまいました。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#tag/token/operation/getTokens
```suggestion
これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#operation/getTokensV2
```

V2のリンクに変えておいてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +
アクセスすると、赤い画面になるとおもいますので、以下の事柄を文章にしていれおいてください。

- 赤い画面にびっくりしないでください
- これから実装していきます

例:  現時点では、http://localhost:3000/tokens にアクセスするとエラー画面が表示されます。安心してください。これからきちんと表示されるように実装を進めて行きます。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#tag/token/operation/issueToken
```suggestion
これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#operation/issueTokenV2
```

V2のリンクに変えておいてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +しばらく（約3分ほど）するとトークンが新規発行され、トークン一覧画面( http://localhost:3000/tokens )に表示されます。
3分はどこから来た数字ですか？
- a. 前回のworkshopのREADMEに3分と書いてあった
- b. 現状動作確認でつかっているテストネットで試してみたところ3分程度でできた

bの場合は、ワークショップでは本番用のTapyrus APIを使いますので、10分に変更しておいてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +http://localhost:3000/wallets でアドレスの一覧が表示されるように実装します。
ここも一旦、エラー画面がでる旨を補足しておいてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +https://doc.api.tapyrus.chaintope.com/#tag/address/operation/getAddresses
```suggestion
https://doc.api.tapyrus.chaintope.com/#operation/getAddresses
```

いつから間違いがあるのか、URLがかわったのかわかりませんが、すべての記載内容に責任をもって確認をしてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#tag/address/operation/createAddress
```suggestion
これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#operation/createAddress
```
いつから間違いがあるのか、URLがかわったのかわかりませんが、すべての記載内容に責任をもって確認をしてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#tag/token/operation/transferToken
```suggestion
これらのコードは、TapyrusAPI の次の機能を呼び出しています。 https://doc.api.tapyrus.chaintope.com/#operation/transferTokenV2
```
V2のリンクに変えておいてください。

2024-05-24 02:39 UTC, yamauchi-haw commented on doc/work2.md
> +このアドレスをトークンの送り主に教えましょう。
Discordにご自身で発行したアドレスをメッセージ投稿してください

等、書いておくと実際にワークショップのときでも進行に合うとおもいます。

2024-05-24 04:24 UTC, tsuruoka91 commented on doc/work2.md
> +しばらく（約3分ほど）するとトークンが新規発行され、トークン一覧画面( http://localhost:3000/tokens )に表示されます。
bです。１０分に修正します。

2024-05-24 05:05 UTC, tsuruoka91 commented on doc/work1.md
> +{:count=>0, :addresses=>[]}
https://github.com/haw/workshop/issues/9 で検討次第で対応が変わると思いますが、ここは最初のあらかじめ実装しておく方が良いと思っています。

理由としては、最初はこのコマンドでTapyrusAPI に接続できているかの確認になるからです。

2024-05-24 07:22 UTC, yamauchi-haw commented on README.md
> +git checkout -b cli origin/workshop20xx (※20xxの部分は年度毎に変更)
workshop2024は、ワークで埋めて欲しいものをmainから抜く形であとで作ればよいので閉じます。

2024-05-24 07:27 UTC, yamauchi-haw approved these changes
いくつか検討事項は残っていますが、Conversationも長くなってきましたし、別のIssueがあるのでこのプルリクエストはマージします。

👍

2024-05-24 08:00 UTC, merged